(deftheme assemblyDruid
  "")

(custom-theme-set-faces
 'assemblyDruid
 '(cursor ((t (:background "DarkSlateGray4"))))
 '(escape-glyph ((t (:foreground "DarkSlateGray4"))))
 '(minibuffer-prompt ((t (:background "gray15" :foreground "DarkSlateGray4" :box nil :family "Hack"))))
 '(highlight ((t (:background "gray95" :foreground "gray15"))))
 '(region ((t (:background "gray15" :foreground "DarkSlateGray4" :family "Hack"))))
 '(font-lock-builtin-face ((t (:background "gray15" :foreground "medium purple"))))
 '(font-lock-comment-delimiter-face ((t (:background "gray15" :foreground "DarkSlateGray4"))))
 '(font-lock-comment-face ((t (:background "gray15" :foreground "DarkSlateGray4"))))
 '(font-lock-preprocessor-face ((t (:background "gray15" :foreground "medium purple"))))
 '(font-lock-warning-face ((t (:inherit error :background "gray15"))))
 '(mode-line ((t (:background "gray18" :foreground "DarkSlateGray4" :box (:line-width 0 :color "DarkSlateGray4")))))
 '(isearch ((t (:background "gray15" :foreground "DarkSlateGray4" :box (:line-width 1 :color "DarkSlateGray4")))))
 '(match ((t (:background "gray15" :foreground "DarkSlateGray4" :box (:line-width 1 :color "DarkSlateGray4")))))
 '(query-replace ((t (:background "gray15" :foreground "DarkSlateGray4" :box (:line-width 1 :color "DarkSlateGray4")))))
 '(default ((t (:inherit nil :stipple nil :background "gray15" :foreground "gray95" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "Hack"))))
 '(fringe ((t (:background "gray15"))))
 '(linum ((t (:background "gray15" :foreground "#696e92"))))
 '(vertical-border ((t (:foreground "#2a2c3e"))))
 '(lazy-highlight ((t (:background "gray15" :foreground "#f9b529" :bold t))))
 '(trailing-whitespace ((t (:inherit show-paren-mismatch-face :underline t))))
 '(mode-line-inactive ((t (:background "gray15" :foreground "#696e92"))))
 '(header-line ((t (:background "gray15" :foreground "#ffffff" :weight bold))))
 '(link ((t (:foreground "#9dbbd3" :weight bold :underline t))))
 '(font-lock-keyword-face ((t (:foreground "gray95" :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "gray95"))))
 '(font-lock-variable-name-face ((t (:foreground "gray95"))))
 '(font-lock-constant-face ((t (:foreground "gray95" :weight bold :italic t))))
 '(font-lock-type-face ((t (:foreground "gray95" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "gray95" :weight bold))))
 '(font-lock-string-face ((t (:foreground "gray95"))))
 '(font-lock-doc-face ((t (:foreground "gray95" :italic t))))
 '(diff-file-header ((t (:background "gray15" :foreground "gray95" :weight bold))))
 '(diff-header ((t (:inherit default :foreground "gray95"))))
 '(diff-indicator-changed ((t (:foreground "gray95" :weight bold))))
 '(diff-changed ((t (:foreground "gray95"))))
 '(diff-indicator-removed ((t (:foreground "gray95" :weight bold))))
 '(diff-removed ((t (:foreground "gray95"))))
 '(diff-indicator-added ((t (:foreground "gray95" :weight bold))))
 '(diff-added ((t (:foreground "gray95"))))
 '(diff-hunk-header ((t (:foreground "gray95"))))
 '(diff-refine-removed ((t (:background "gray15" :foreground "gray95" :weight bold))))
 '(diff-refine-added ((t (:background "gray15" :foreground "gray95" :weight bold))))
 '(diff-refine-changed ((t (:background "gray15" :foreground "gray95" :weight bold)))))

(provide-theme 'assemblyDruid)
